// create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "AhmedBitar@gmail.com",
    "password": "somethinghere"
}

### sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "AhmedBitar@gmail.com",
    "password": "somethinghere"
}

### Sign out
POST http://localhost:3000/auth/sign-out
Content-Type: application/json

{
    "email": "AhmedBitar@gmail.com",
    "password": "somethinghere"
}

### Get currently sign in user
GET  http://localhost:3000/auth/who-am-i
Content-Type: application/json

{
    "email": "AhmedBitar@gmail.com",
    "password": "somethinghere"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "Ahmed@gmail.com",
    "password": "somethinghere"
}

### Find by id query
GET http://localhost:3000/auth/15
Content-Type: application/json


### Find by query email
GET http://localhost:3000/auth?email=qwe@nemail.som
Content-Type: application/json



### Delete a user by ID
DELETE http://localhost:3000/auth/5
Content-Type: application/json

### Update a user
PATCH http://localhost:3000/auth/5
Content-Type: application/json

{
    "email": "aaa@aaaa.som",
    "password": "somthing"
}
